title: The tTIle
author: fish
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  The description

# social links
twitter_username: ysamoeyd
github_username:  ysamoeyd

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
